services:
  postgres:
    image: postgres:17.3
    container_name: postgres-laravel
    restart: always
    ports:
      - 5432:5432
    networks:
      laravel-net:
        ipv4_address: 172.16.238.15
    volumes:
      - /opt/database/logerr:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=logerr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=nr04wDdk1D
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbit-laravel
    ports:
      - 5672:5672
      - 15673:15672
    networks:
      laravel-net:
        ipv4_address: 172.16.238.16
  php:
    container_name: php-laravel
    volumes:
      - '/var/www/logerr:/var/www/logerr'
      - ./env.ini:/var/www/logerr/.env:z
    ports:
      - 9000:9000
    build:
      dockerfile: laravel.dock
    entrypoint: ["sh", "./init.sh"]
    networks:
      - laravel-net
    depends_on:
       - postgres
       - redis
  nginx:
    image: nginx
    container_name: nginx-laravel
    restart: always
    ports:
      - 80:80
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - '/var/www/logerr:/var/www/logerr'
    networks:
      - laravel-net
    depends_on:
       - php
  artisan_rabbit_logs:
    container_name: artisan-rabbit-logs
    build: 
      dockerfile: php.dock
    working_dir: '/var/www/logerr'
    restart: unless-stopped
    volumes:
      - '/var/www/logerr:/var/www/logerr'
    entrypoint: ["php", "artisan", "rabbit:logs"]
    networks:
      - laravel-net
    depends_on:
      - php
      - rabbitmq
  artisan_rabbit_errors:
    container_name: artisan-rabbit-errors
    build:
      dockerfile: php.dock
    working_dir: '/var/www/logerr'
    restart: unless-stopped
    volumes:
      - '/var/www/logerr:/var/www/logerr'
    entrypoint: [ "php", "artisan", "rabbit:errors" ]
    networks:
      - laravel-net
    depends_on:
      - php
      - rabbitmq
  artisan_notifications:
    container_name: artisan-notifications
    build: 
      dockerfile: php.dock
    working_dir: '/var/www/logerr'
    restart: unless-stopped
    volumes:
      - '/var/www/logerr:/var/www/logerr'
    entrypoint: ["php", "artisan", "notification:handle"]
    networks:
      - laravel-net
    depends_on:
      - php
  artisan_report:
    container_name: artisan-report
    build:
      dockerfile: php.dock
    working_dir: '/var/www/logerr'
    restart: unless-stopped
    volumes:
      - '/var/www/logerr:/var/www/logerr'
    entrypoint: [ "php", "artisan", "report:calculate" ]
    networks:
      - laravel-net
    depends_on:
      - php
  redis:
    image: redis:7.4.3
    container_name: redis-laravel
    command: redis-server --maxmemory 4100mb --maxmemory-policy allkeys-lru
    mem_limit: 4000mb
    ports:
      - 6379:6379
      - 8001:8001
    networks:
      - laravel-net
networks:
  laravel-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24

        